apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: random-string-generator
  name: random-string-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-string-generator
  strategy: {}
  template:
    metadata:
      labels:
        app: random-string-generator
    spec:
      containers:
        - image: lucksei/random-string-generator:latest
          name: random-string-generator
          resources: {}
status: {}
