apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-pvc
spec:
  # storageClassName: StorageClass # Do NOT use this specifier as GKE will provision the PV dynamically 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
