apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-backend-postgres
  namespace: project
spec:
  selector:
    matchLabels:
      app: todo-backend-postgres
  serviceName: todo-backend-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-backend-postgres
    spec:
      containers:
        - image: postgres:15.15-alpine3.22
          name: todo-backend-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
              name: web
          volumeMounts:
            - name: todo-backend-postgres-data
              mountPath: /var/lib/postgresql
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: todo-backend-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: todo-backend-secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: todo-backend-secret
  volumeClaimTemplates:
    - metadata:
        name: todo-backend-postgres-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-postgres-svc
  namespace: project
spec:
  selector:
    app: todo-backend-postgres
  ports:
    - port: 5432
      targetPort: 5432
