apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secret
  namespace: project
data:
  # Secrets for the todo-backend-postgres
  POSTGRES_PASSWORD: dG9kbw== # todo
  POSTGRES_USER: dG9kbw== # todo
  POSTGRES_DB: dG9kbw== # todo
  # Secrets for the todo-backend
  # DATABASE_URI: cG9zdGdyZXNxbDovL3RvZG86dG9kb0B0b2RvLWJhY2tlbmQtcG9zdGdyZXMtc3ZjOjU0MzIvdG9kbw== # postgresql://todo:todo@todo-backend-postgres-svc:5432/todo
  DATABASE_URI: cG9zdGdyZXNxbDovL3RvZG86dG9kb0B0b2RvLWJhY2tlbmQtcG9zdGdyZXMtc3ZjOjU0MzIvdG9kbw== # postgresql://postgres:todo@127.0.0.1:5432/postgres
# NOTE: encode with:
# echo -n '...' | base64
# NOTE: decode with:
# echo '...' | base64 -d
