apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secret
  namespace: project
data:
  # Secrets for the todo-backend-postgres
  POSTGRES_PASSWORD: dG9kbw== # todo
  POSTGRES_USER: dG9kbw== # todo
  POSTGRES_HOST: dG9kby1iYWNrZW5kLXBvc3RncmVzLXN2Yw== # todo-backend-postgres-svc
  POSTGRES_DB: dG9kbw== # todo
  # Secrets for the todo-backend
  DATABASE_URI: cG9zdGdyZXNxbDovL3RvZG86dG9kb0B0b2RvLWJhY2tlbmQtcG9zdGdyZXMtc3ZjOjU0MzIvdG9kbw== # postgresql://todo:todo@todo-backend-postgres-svc:5432/todo
  # NOTE: Uncomment to use wrong password for testing 
  # DATABASE_URI: cG9zdGdyZXNxbDovL3RvZG86d3JvbmdwYXNzd29yZEB0b2RvLWJhY2tlbmQtcG9zdGdyZXMtc3ZjOjU0MzIvdG9kbw== # postgresql://todo:wrongpassword@todo-backend-postgres-svc:5432/todo
  # NOTE: Uncomment to use Cloud SQL Proxy
  # DATABASE_URI: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRvZG9AMTI3LjAuMC4xOjU0MzIvcG9zdGdyZXM= # postgresql://postgres:todo@127.0.0.1:5432/postgres
  NATS_URI: bmF0czovL215LW5hdHMubmF0cy5zdmMuY2x1c3Rlci5sb2NhbDo0MjIy # nats://my-nats.nats.svc.cluster.local:4222
  DISCORD_WEBHOOK_URL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQyNDQxNzgwODUwNjI5MDI3OS9MbmJ0NXo2dVhhOUh4R0M0LUVadmNXSFNVZi1oU0RMeEdCaFAwdVFiQ2oyWDYwY3NpM1Bsdk9iTjJSTTU2OEVTQklraA== # https://discord.com/api/webhooks/1424417808506290279/Lnbt5z6uXa9HxGC4-EZvcWHSUf-hSDLxGBhP0uQbCj2X60csi3PlvObN2RM568ESBIkh

# NOTE: encode with:
# echo -n '...' | base64
# NOTE: decode with:
# echo '...' | base64 -d
