apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pingpong
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  strategy: {}
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      # volumes:
      #   - name: my-local-pvc
      #     persistentVolumeClaim:
      #       claimName: my-local-pvc
      containers:
        - name: pingpong
          image: lucksei/pingpong:latest
          resources: {}
          # volumeMounts:
          #   - name: my-local-pvc
          #     mountPath: /usr/src/app/data
          env:
            - name: PORT
              value: '3000'
