apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
patches:
- path: ./manifests/gateway.yaml
- path: ./todo-broadcaster/manifests/configMap.yaml
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: main-537532e744c4ecb0274c20e4e644e9af5f7a6805
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: main-537532e744c4ecb0274c20e4e644e9af5f7a6805
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: main-537532e744c4ecb0274c20e4e644e9af5f7a6805
