apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
patches:
- path: ./manifests/gateway.yaml
- path: ./todo-broadcaster/manifests/configMap.yaml
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: main-f132f62cbd1b8403730c945f860ddb43da4b9a66
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: main-f132f62cbd1b8403730c945f860ddb43da4b9a66
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: main-f132f62cbd1b8403730c945f860ddb43da4b9a66
