apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: main-c3ab00d5733387f8bd85c5b68003852f211b5a21
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: main-c3ab00d5733387f8bd85c5b68003852f211b5a21
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: main-c3ab00d5733387f8bd85c5b68003852f211b5a21
