apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: main-e20f8c960bcc980af557d1c7091b2c03ada03ff9
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: main-e20f8c960bcc980af557d1c7091b2c03ada03ff9
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: main-e20f8c960bcc980af557d1c7091b2c03ada03ff9
