apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: main-4c4b511041cab80dc824800e48bc4db0ff6bc87e
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: main-4c4b511041cab80dc824800e48bc4db0ff6bc87e
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: main-4c4b511041cab80dc824800e48bc4db0ff6bc87e
