apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: main-de7023fdceb171d927d98cdf543e7b141dca9865
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: main-de7023fdceb171d927d98cdf543e7b141dca9865
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: main-de7023fdceb171d927d98cdf543e7b141dca9865
