apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-configmap
  namespace: exercises
data:
  information.txt: |
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.
  MESSAGE: 'Hello world!'
  PORT: '3000'
  LOG_FILE_PATH: './data/pod.log'
  PINGPONG_URL: 'http://pingpong-svc:80/pings'
  GREETINGS_URL: 'http://greeter-svc:3000' 
  INFORMATION_FILE_PATH: './data/information.txt'
