apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: log-output
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  strategy: {}
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: information
          configMap:
            name: log-output-cm
            items:
              - key: information.txt
                path: information.txt
      containers:
        - image: lucksei/log-output-container0:latest
          name: log-output-container0
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
          resources: {}
        - image: lucksei/log-output-container1:latest
          name: log-output-container1
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
            - name: information
              mountPath: /usr/src/app/data/information.txt
              subPath: information.txt
              readOnly: true
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            httpGet:
              path: /healthz
              port: 3000
          envFrom:
            - configMapRef:
                name: log-output-cm
          resources: {}
status: {}
