apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-cm
data:
  # Common
  NODE_ENV: production
  # Server env vars
  STATIC_DIR: dist
  DATA_DIR: /usr/src/data
  HOURLY_IMAGE_REFRESH_INTERVAL_SECONDS: '600'
  PORT: '3000'
  LOREM_PICSUM_URL: https://picsum.photos/1200/400
  LOREM_PICSUM_IMAGE_NAME: 'hourly.jpg'
