apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: my-local-pvc
          persistentVolumeClaim:
            claimName: my-local-pvc
      containers:
        - image: lucksei/todo-app:latest
          imagePullPolicy: Always
          name: todo-app
          volumeMounts:
            - name: my-local-pvc
              mountPath: /usr/src/data
          resources: {}
          env:
            - name: PORT
              value: '3000'
status: {}
