# Deprecated: Using gateway API instead, new dir path exercises/manifests/gateway.yaml & project/manifests/gateway.yaml
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: exercises-ingress
#   namespace: exercises
# spec:
#   rules:
#     - http:
#         paths:
#           - path: '/pingpong'
#             pathType: Prefix
#             backend:
#               service:
#                 name: pingpong-svc
#                 port:
#                   number: 80
#           - path: '/status'
#             pathType: Prefix
#             backend:
#               service:
#                 name: log-output-svc
#                 port:
#                   number: 80