apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: exercises-gateway
  namespace: exercises
spec:
  gatewayClassName: gke-l7-gxlb # Or gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pingpong-route
  namespace: exercises
spec:
  parentRefs:
    - name: exercises-gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /pingpong
      backendRefs:
        - name: pingpong-svc
          port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /status
      backendRefs:
        - name: log-output-svc
          port: 80