apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: todo-app-svc
                port:
                  number: 3000
          - path: '/pingpong'
            pathType: Prefix
            backend:
              service:
                name: pingpong-svc
                port:
                  number: 3000
          - path: '/status'
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 2345
