# # NOTE: Deprrecated for GKE, which provisions Persistent Disks automatically
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: my-local-pv
# spec:
#   storageClassName: my-local-pv
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   local:
#     path: /tmp/kube
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - k3d-k3s-default-agent-0
