# # NOTE: Not using this for now
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: my-local-pvc
# spec:
#   storageClassName: my-local-pv
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100M
