apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-production 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucksei/k8s-submissions-chapter2
    path: project/overlays/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucksei/k8s-submissions-chapter2
    path: project/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true