apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: exercises-gateway
  namespace: exercises
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pingpong-route
  namespace: exercises
spec:
  parentRefs:
    - name: exercises-gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /pingpong
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: pingpong-svc
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: log-output-route
  namespace: exercises
spec:
  parentRefs:
    - name: exercises-gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /status
      backendRefs:
        - name: log-output-svc
          port: 80

# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: greeter-route
#   namespace: exercises
# spec:
#   parentRefs:
#     - group: ""
#       kind: Service
#       name: greeter-svc
#       port: 3000
#   rules:
#     - backendRefs:
#       - name: greeter-svc-v1
#         port: 3000
#         weight: 50
#       - name: greeter-svc-v2
#         port: 3000
#         weight: 50


# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: greeter-route 
#   namespace: exercises
# spec:
#   parentRefs:
#     - name: exercises-gateway
#   rules:
#     - matches:
#       - path:
#           type: Exact
#           value: /
#       backendRefs:
#         - name: greeter-v1-svc
#           port: 3000
#           weight: 75
#         - name: greeter-v2-svc
#           port: 3000
#           weight: 25