apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: greeter-svc
spec:
  parentRefs:
    - group: ""
      kind: Service
      name: greeter-svc
      port: 3000 
  rules:
    - backendRefs:
        - name: greeter-svc-v1
          port: 3000
          weight: 75
        - name: greeter-svc-v2
          port: 3000
          weight: 25