apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises
resources:
- ./manifests/gateway.yaml
- ./manifests/trafficHttpRoute.yaml
# - ./manifests/gatewayNginx.yaml
- ./pingpong/manifests/database.yaml
# - ./pingpong/manifests/deployment.yaml
- ./pingpong/manifests/service.yaml
- ./pingpong/manifests/knativeService.yaml
- ./log-output/manifests/configMap.yaml
- ./log-output/manifests/deployment.yaml
- ./log-output/manifests/service.yaml
- ./greeter/manifests/deployment.yaml
- ./greeter/manifests/service.yaml
- ./greeter/manifests/versions.yaml
- ./randomwiki/manifests/configMap.yaml
- ./randomwiki/manifests/deployment.yaml
- ./randomwiki/manifests/service.yaml