apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises
resources:
- ./manifests/gateway.yaml
- ./pingpong/manifests/analysisTemplate.yaml
- ./pingpong/manifests/database.yaml
- ./pingpong/manifests/deployment.yaml
- ./pingpong/manifests/service.yaml
- ./log-output/manifests/configMap.yaml
- ./log-output/manifests/deployment.yaml
- ./log-output/manifests/service.yaml
- ./greeter/manifests/deployment.yaml
- ./greeter/manifests/service.yaml