apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

  # Exercises Level
  
  # Ping-Pong App

  # Log Output App
resources:
- ./manifests/gateway.yaml
- ./pingpong/manifests/analysisTemplate.yaml
- ./pingpong/manifests/database.yaml
- ./pingpong/manifests/deployment.yaml
- ./pingpong/manifests/service.yaml
- ./log-output/manifests/configMap.yaml
- ./log-output/manifests/deployment.yaml
- ./log-output/manifests/service.yaml
images:
- name: lucksei/log-output-container0
  newName: lucksei/log-output-container0
  newTag: main-e435fd7997cbe270ce354a24200c2fb68770b8a9
- name: lucksei/log-output-container1
  newName: lucksei/log-output-container1
  newTag: main-e435fd7997cbe270ce354a24200c2fb68770b8a9
