apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: project-gateway
  namespace: project
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: todo-app-route
  namespace: project
spec:
  parentRefs:
    - name: project-gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: todo-app-svc
          port: 3000

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: todo-backend-route
  namespace: project
spec:
  parentRefs:
    - name: project-gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /api
      backendRefs:
        - name: todo-backend-svc
          port: 3000