apiVersion: v1
kind: Service
metadata:
  name: greeter-v1-svc
spec:
  selector:
    app: greeter
    version: v1
  ports:
  - name: http
    port: 3000 
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: greeter-v2-svc
spec:
  selector:
    app: greeter
    version: v2
  ports:
  - name: http
    port: 3000 
    targetPort: 3000
