apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
  namespace: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: lucksei/todo-broadcaster:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: NATS_URI 
              valueFrom:
                secretKeyRef:
                  name: todo-broadcaster-secret
                  key: NATS_URI
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: todo-broadcaster-secret
                  key: DISCORD_WEBHOOK_URL
            - name: FORWARDS_TO_DISCORD
              valueFrom:
                configMapKeyRef:
                  name: todo-broadcaster-configmap
                  key: FORWARDS_TO_DISCORD