apiVersion: v1
kind: Secret
metadata:
  name: todo-broadcaster-secret
  namespace: project
data:
  NATS_URI: bmF0czovL215LW5hdHMubmF0cy5zdmMuY2x1c3Rlci5sb2NhbDo0MjIy # nats://my-nats.nats.svc.cluster.local:4222
  DISCORD_WEBHOOK_URL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQyNDQxNzgwODUwNjI5MDI3OS9MbmJ0NXo2dVhhOUh4R0M0LUVadmNXSFNVZi1oU0RMeEdCaFAwdVFiQ2oyWDYwY3NpM1Bsdk9iTjJSTTU2OEVTQklraA== # https://discord.com/api/webhooks/1424417808506290279/Lnbt5z6uXa9HxGC4-EZvcWHSUf-hSDLxGBhP0uQbCj2X60csi3PlvObN2RM568ESBIkh

# NOTE: encode with:
# echo -n '...' | base64
# NOTE: decode with:
# echo '...' | base64 -d
