apiVersion: v1
kind: Secret
metadata:
    name: todo-backend-secret
data:
    DATABASE_URI: ENC[AES256_GCM,data:7QweXgGr1b4eU6EllfOkhW0wOXpH/3oMSzTy2J6L9GKViT91b0JhhwIcd/RzgbmfjuU4dwO9sIXheuF7bbeRlIfLfKaQVQU3POW9zQ==,iv:4UV8DNyT/QYlf2SyhT+HoK2AucXgGLk4e5PlW/L/UVM=,tag:3+EajK4aRLpb7jtCdqOxEQ==,type:str]
# NOTE: for secrets use: echo -n '...' | base64
sops:
    age:
        - recipient: age1724zv9r34nesytj5tstjepkmyl26kcxwdumctuf82plfg4ft4e8qcnwgcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bWU4YmVya2NESVM2U2Mw
            Nk50Q2VuNEo2U3RRUFRqY2p0YjJkRWRuTVg4Cmc1WldTc25WZWsyZllOQm44OHV5
            VHRZVFlzem9tNUwzZDI4ODIwUFJPdjgKLS0tIDJ5TUJML1Zqb0ZLWkp3c3NWT3NX
            b2VwamxKWXRWNXRuSFZwYnVhMGJma2MKKpGyVgKA+d0M+W+PgiHly5JxSqF0tP0E
            5RP5U/vUIlu4fwiZR03pHP6AwLhv2/CjhAWhPy4smtxpTNGCMS0bTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T19:37:04Z"
    mac: ENC[AES256_GCM,data:YMiWE2ncX0HpT+FEq6qx/ZaK1Vt4Pu+xIlojzujyRY6GUnUOAeyKzBWyXRmpfUF/gu+E0zmOZXv35vriphf+Xl4KgFNoCVhBJQttH8rwDsVsc67BzyPppPR7fxWbJSLna89iy30Y7VIueOTku3lioUNUISOnuy79Ei+wMtA58vE=,iv:jMxCQOS1rr3JRZSLzaEQ6pXaNBI0XvrNFJtbO7PrLEE=,tag:20LPTYTAlMjkorIIkcIvFg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
