apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- ./todo-backend/manifests/backupsCronJob.yaml
- ./todo-broadcaster/manifests/configMap.yaml
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: 4.9-6bba80327c74ac12aa3ebe153150f564aa7cbc89
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: 4.9-6bba80327c74ac12aa3ebe153150f564aa7cbc89
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: 4.9-6bba80327c74ac12aa3ebe153150f564aa7cbc89
