apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- ./todo-backend/manifests/backupsCronJob.yaml
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: 4.9-d338eeb6d226a5e9801dd65d52b19bac27e52036
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: 4.9-d338eeb6d226a5e9801dd65d52b19bac27e52036
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: 4.9-d338eeb6d226a5e9801dd65d52b19bac27e52036
