apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- ./todo-backend/manifests/backupsCronJob.yaml
- ./todo-broadcaster/manifests/configMap.yaml
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: 4.10-ca6649173babca37ccb645e9867f740c07a86a5e
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: 4.10-ca6649173babca37ccb645e9867f740c07a86a5e
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: 4.10-ca6649173babca37ccb645e9867f740c07a86a5e
