apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- ./todo-backend/manifests/backupsCronJob.yaml
- ./todo-broadcaster/manifests/configMap.yaml
images:
- name: lucksei/todo-app
  newName: lucksei/todo-app
  newTag: 4.9-e4fc6e063ddee0e9056e2cffcb1be747dcc82727
- name: lucksei/todo-backend
  newName: lucksei/todo-backend
  newTag: 4.9-e4fc6e063ddee0e9056e2cffcb1be747dcc82727
- name: lucksei/todo-broadcaster
  newName: lucksei/todo-broadcaster
  newTag: 4.9-e4fc6e063ddee0e9056e2cffcb1be747dcc82727
