name: Release application

on:
  push:

env: 
  BRANCH: ${{ github.ref_name }}
  GITHUB_SHA: ${{ github.sha }}
  # TODO

jobs:
  build-and-publish:
    name: Build & Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Debug secrets
        run: |
          echo "Username length: ${#DOCKERHUB_USERNAME}"
          echo "Password length: ${#DOCKERHUB_TOKEN}"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      
      - name: 'Build and push "todo-app"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-app
          file: ./project/todo-app/Dockerfile
          push: true
          tags: "lucksei/todo-app:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"
      
      - name: 'Build and push "todo-backend"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-backend
          file: ./project/todo-backend/Dockerfile
          push: true
          tags: "lucksei/todo-backend:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"
      
      - name: 'Build and push "todo-broadcaster"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-broadcaster
          file: ./project/todo-broadcaster/Dockerfile
          push: true
          tags: "lucksei/todo-broadcaster:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      
      - name: 'Use the right image'
        run: |
          kustomize edit set image lucksei/todo-app=lucksei/todo-app:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/todo-backend=lucksei/todo-backend:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/todo-broadcaster=lucksei/todo-broadcaster:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}
