name: Release application locally 

on:
  push:

env: 
  BRANCH: ${{ github.ref_name }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  # For the "exercises"
  build-and-publish:
    name: Build & Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      
      - name: 'Build and push "log-output-container0"'
        uses: docker/build-push-action@v6
        with:
          context: ./exercises/log-output
          file: ./exercises/log-output/Dockerfile.container0
          push: true
          tags: "lucksei/log-output-container0:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"

      - name: 'Build and push "log-output-container1"'
        uses: docker/build-push-action@v6
        with:
          context: ./exercises/log-output
          file: ./exercises/log-output/Dockerfile.container1
          push: true
          tags: "lucksei/log-output-container1:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      
      - name: 'Use the right image'
        run: |
          cd exercises
          kustomize edit set image lucksei/log-output-container0=lucksei/log-output-container0:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/log-output-container1=lucksei/log-output-container1:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'exercises/kustomization.yaml'
          message: New version released ${{ github.sha }}
      
      # For the "project"
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      
      - name: 'Build and push "todo-app"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-app
          file: ./project/todo-app/Dockerfile
          push: true
          tags: "lucksei/todo-app:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"
      
      - name: 'Build and push "todo-backend"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-backend
          file: ./project/todo-backend/Dockerfile
          push: true
          tags: "lucksei/todo-backend:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"
      
      - name: 'Build and push "todo-broadcaster"'
        uses: docker/build-push-action@v6
        with:
          context: ./project/todo-broadcaster
          file: ./project/todo-broadcaster/Dockerfile
          push: true
          tags: "lucksei/todo-broadcaster:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      
      - name: 'Use the right image'
        run: |
          cd project
          kustomize edit set image lucksei/todo-app=lucksei/todo-app:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/todo-backend=lucksei/todo-backend:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
          kustomize edit set image lucksei/todo-broadcaster=lucksei/todo-broadcaster:${{ env.BRANCH }}-${{ env.GITHUB_SHA }}
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: '*/kustomization.yaml'
          message: New version released ${{ github.sha }}